extends:
  - eslint:recommended
  - plugin:jest/recommended
env:
  es2022: true
  node: true
  jest/globals: true
plugins:
  - jest
rules:
  complexity:
    - error
    - 10
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - 2
    - never
    - beforeStatementContinuationChars: always
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
