extends:
  - eslint:recommended
  - plugin:jest/recommended
env:
  es6: true
  node: true
  jest/globals: true
plugins:
  - jest
rules:
  complexity:
    - error
    - 10
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
