org: drflamerock
app: clip-gift-backend
service: clip-gift-backend
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  api:
    handler: src/utility/handlers/clip.handler
    events:
      - httpApi:
          path: /clip
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-scripts
  - serverless-stack-output

custom:
  output:
    handler: scripts/output.handler
    file: ./build/stack-env.json

  scripts:
    hooks:
      - cat ./build/stack-env.json
      - 'deploy:finalize': newman run fixtures/clipgift-endpoint-tests.postman_collection.json -e ./build/stack-env.json
