org: drflamerock
app: clip-gift-backend
service: clip-gift-backend
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    API_URL: !GetAtt HttpApi.ApiEndpoint

functions:
  api:
    handler: src/utility/handlers/clip.handler
    events:
      - httpApi:
          path: /clip
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-scripts

custom:
  scripts:
    print: echo self:provider.environment.API_URL
    hooks:
      'deploy:finalize': print
