org: drflamerock
app: clip-gift-backend
service: clip-gift-backend
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /clip
          method: get

plugins:
  - serverless-offline
