org: drflamerock
app: clip-gift-backend
service: clip-gift-backend
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  api:
    handler: src/utility/handlers/clip.handler
    events:
      - httpApi:
          path: /clip
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      'deploy:finalize': newman run fixtures/clipgift-endpoint-tests.postman_collection.json --env-var "endpoint=${cf:${sls:service}-${sls:stage}.HttpApiUrl}"
